-- The Hartnell TARDIS (Classic Doors)

local T = {
	ID = "hartnelltardis_cl",
	Base="hartnelltardis",
	Name="The Hartnell TARDIS (Classic Doors)",
	IsVersionOf="hartnelltardis"
}

T.EnableClassicDoors = true
T.Interior={
	Portal={ -- Generated by portals debug tool
		pos = Vector(259.75, 150.125, 54.375),
		ang = Angle(-0, -149.99633789063, 0),
		width = 300,
		height = 150,
	},
	Fallback={
		pos = Vector(234.7, 137.5, 12),
	},
	Sounds={
		Door={
			enabled=true,
			open="torrent/hartnell/main/bigdoor.ogg",
			close="torrent/hartnell/main/bigdoor.ogg",
		},
	},
	Parts={
		intdoor={
			model = "models/torrent/hartnell/bigdoor.mdl",
			ang = Angle(0,-120,0),
		},
		newhartnellbigdoormain=false,
	},
	IntDoorAnimationTime = 4.5,
}

TARDIS:AddInterior(T)
